dataDirectory: "/media/storage/bcurran/classifiers/methylation/data/"
resultsDirectory: "/media/storage/bcurran/classifiers/methylation/results/models/"
datafile: "/media/storage/bcurran/classifiers/methylation/data/methylationHG38FilteredMValue.h5ad"
#filteredDataFile: /data/projects/classifiers/methylation/data/baseMethylationBetaValuesFiltered.parquet
filteredMValueFile: /media/storage/bcurran/classifiers/methylation/data/methylationMValuesFiltered.parquet

grid_search_config:
  scoring: 'accuracy'
  n_splits: 3
  n_jobs: 10
  verbose: 2
  error_score: 'raise'

model_configs:
  svm:
    parameters:
      decision_function_shape: 'ovo'
      random_state: 42
      cache_size: 500
    parameter_grid:
      modelRefinement__C: [0.1, 1, 10]
      modelRefinement__kernel: ['linear', 'rbf']
      modelRefinement__gamma: ['scale', 'auto']

  random_forest:
    parameters:
      random_state: 42
      n_jobs: -1
    parameter_grid:
      modelRefinement__n_estimators: [100, 200, 300]
      modelRefinement__max_depth: [null, 10, 20]
      modelRefinement__criterion: ['gini', 'entropy']
      modelRefinement__max_features: [null, 'sqrt', 'log2']
      modelRefinement__min_samples_split: [2, 5, 10]
      modelRefinement__class_weight: [null, 'balanced']

  #modelRefinement__kernel:
  #  - linear
  #  - poly
  #  - rbf
  #  - sigmoid
  #modelRefinement__max_depth:
  #  - 
  #  - 10
  #  - 20
  #modelRefinement__criterion:
  #  - gini
  #  - log_loss
  #  - entropy
  #modelRefinement__max_features:
  #  - 
  #  - sqrt
  #  - log2
  #odelRefinement__class_weight:
  #  - 
  #  - balanced
  #  - balanced_subsample
